import React from 'react';

import {connect} from "react-redux";
import {getTranslate} from 'react-localize-redux';

import withRouter from "react-router-dom/es/withRouter";

import Navbar from '../../components/bars/Navbar/Navbar.jsx'
import Footer from '../../components/bars/Footer/Footer.jsx'
import { Container } from '../../widgets/Container/Container.jsx';
import { PageWrapper } from '../../widgets/PageWrapper/PageWrapper.jsx';

require("style-loader!./PrivacyPage.scss");

class PrivacyPage extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      email: '',
    };

    this.validateEmail = this.validateEmail.bind(this);
  }

  componentDidMount() {

  }

  render() {
    return (
      <PageWrapper>
        <Navbar size={Container.sizes.SMALL}/>

        <Container className={'tos-page'} size={Container.sizes.TEXT}>
          <h1>CUBEGO'S USERS’S PRIVACY AND DATA PROTECTION POLICY (THE “POLICY”)</h1>

          <h3>1. PRIVACY POLICY STATEMENT</h3>
          <p>1.1. Cubego (“Cubego”, the “Business”, “We”, “Our” or “Us”) respects your legal rights to personal data protection when We collect, transfer, store, or access your personal data.</p>
          <p>1.2. This Privacy Policy Statement outlines the Business’ practices in relation to the collection, storage, use, processing and disclosure of personal data (as defined under the Personal Data Protection Act 2012 (“PDPA”) through our website located at https://www.cubego.io (the “Website”).</p>
          <p>1.3. By visiting, accessing, or using the Website, you (“user”, “you”, or “your”) have indicated that you are at least eighteen (18) years old, have the legal capacity to consent to this Policy, and to agree to be bound by the policies and practices of this Policy in their entirety. This Policy sets out the following:</p>
          <ul>
          <li>(a) The types of personal data being collected and the sources from which We collect such personal data;</li>
          <li>(b) The purposes for collection, use and disclosure of personal data;</li>
          <li>(c) Disclosure of personal data;</li>
          <li>(d) Care of personal data (accuracy, protection, retention and transfer); and</li>
          <li>(e) The process by which We receive and respond to any feedback that may arise with respect to the collection, storage, use, processing and disclosure of personal data.</li>
          </ul>

          <h3>2. COLLECTION OF PERSONAL AND OTHER INFORMATION</h3>
          <p>2.1. Non-Personal Data: If the User chooses to use the Website, the User consents to allowing the Business to collect information about the User’s activities and trends through the Website. Such information may include (a) Device Information: Information that is automatically collected about your device, such as, but not limited to, your browser’s name and technical information about your means of connection to the Website, in particular hardware, operating system, browser, among other similar information; (b) Location Information: Information that is automatically collected via analytics systems providers to determine your location, including your IP address and/or domain name and any external page that referred you to Us; (c) Log Information: Information that is generated by your use of the Website that is automatically collected and stored in our server logs. This may include, but is not limited to, device-specific information, location information, system activity and any internal and external information related to the Website that you visit; and (d) Account Information: Information that is generated by your account activity on the Website including, but not limited to, purchase activity, trading activity, deposits, withdrawals, and account balances. This information is aggregated to provide statistical data about our users' browsing actions and patterns, and does not personally identify individuals.</p>
          <p>2.2. The User expressly agrees and acknowledges that the Business shall collect and store the User’s personal information including but not limited to the User’s email address, name, phone number, and additional information or documentation for verification at the discretion of our Compliance Team (“User Information”).</p>
          <p>2.3. Such User Information may come within the meaning of “personal data” as defined in the PDPA and as used in this Policy. The User acknowledges that your User Information may be used by the Business to provide services and features targeted at the User, that are most likely to meet the User’s needs, and to customise and improve the Website and the experiences of you and other users of the Website (but these other users will not see or have access to your User Information).</p>
          <p>2.4. The User is aware that any and all information pertaining to the User collected by the Business, whether or not directly provided by the User to the Business (via the Website or otherwise), including but not limited to personal correspondence such as emails or letters, instructions from the User relating to the Services, or communications between the User and other users, as well as information that you provide to us in correspondence with respect to ongoing customer support may be collected and compiled by the Business and you hereby expressly consent to the same.</p>
          <p>2.5. Cookies: The Business collects data by way of ‘cookies’. Cookies are small data files which are sent to the User’s browser from the Website and are stored on the User’s computer or device (hard drive). The cookies shall not provide access to data in the User’s computer or device (hard drive), such as email address or any other data that can be traced to the User personally. The data collected by way of cookies will allow us to administer the Website and provide a tailored and user-friendly service to the Users. Information collected from cookies is used by us to evaluate the effectiveness of the Website, analyse trends, and administer the Website. The information collected from cookies allows the Business to determine such things as which parts of the Website are most visited and difficulties our visitors may experience in accessing the Website. With this knowledge, the Business aims to improve the quality of the User’s experience on the Website by recognising and delivering the most desired features and information. In addition to cookies, the Business may also use a technology known as web bugs or clear gifs, which are typically stored in emails to help confirm receipt of, and response to, the emails sent by the Business and to provide the User with a personalised experience while accessing the Website. you agree to the use of cookies by continuing to use the Website and any platform operated by the Business.</p>
          <p>2.6. The cookies shall enable the Users to access certain features or services of the Website. Most web browsers and devices can be set to notify when a User receives a cookie or to prevent cookies from being sent; if the User accepts such features, it may limit the functionality that the Business can provide when a User visits the Website.</p>
          <p>2.7. We may also collect or otherwise be provided with User Information about you from third parties whose websites you visit or whose services you use, including as social media platforms, where you may have authorized such websites and platforms to collect and share your User Information.</p>

          <h3>3. USE OF THE INFORMATION COLLECTED</h3>
          <p>3.1. We may use the User Information to:</p>
          <ul>
            <li>(a) Provide the User with the use of the Website and the services offered on the Website, including customer support for Cubego;</li>
            <li>(b) Optimise and enhance the Website or any websites or platform operated by the Business or its affiliates, for all users, or for you specifically;</li>
            <li>(c) Conduct anti-fraud, anti-money laundering, countering of terrorist financing, and identity verification and authentication Know-your-Customer checks (you authorise us to share your information with our third-party service providers, when applicable, who may also conduct their own searches about you);</li>
            <li>(d) Monitor the usage of the Website, and conduct automated and manual security checks of our service; and</li>
            <li>(e) Create aggregated and anonymised reporting data about the Business.</li>
          </ul>

          <p>3.2. The Business will handle personal data appropriately, in line with the circumstances and in accordance with applicable law in Singapore, including the PDPA. If any intended use of personal data will go beyond the purposes envisioned during collection, the Business will notify Users of the new purpose(s) and seek consent to use their personal data for such purpose(s).</p>

          <h3>4. SUBMISSIONS</h3>
          <p>4.1. We cannot agree to obligations of confidentiality or nondisclosure with regard to any unsolicited information the User submits to Us, regardless of the method or medium chosen. By submitting unsolicited information or materials to us or Cubego’s service providers, you or anyone acting on your behalf, agree that any such information or materials will not be considered confidential or proprietary.</p>
          <p>4.2. We do not provide any facility for sending or receiving private or confidential electronic communications. you should not use the Website to transmit any communication for which you intend only for you and the intended recipient(s) to read. Notice is hereby given that all messages and other content entered using the Website can and may be read by us, regardless of whether we are the intended recipients of such messages. Nevertheless, access to messages and other content will be accessible only by the authorised personnel of the Business and Cubego service providers that reasonably need such access.</p>

          <h3>5. SECURITY AND RETENTION OF PERSONAL INFORMATION</h3>
          <p>5.1. We protect the personal data in our possession or under our control by making reasonable and practical security arrangements to protect the User’s personal information from unauthorised access, collection, use, disclosure, copying, modification, disposal or similar. Unfortunately, however, no data transmission over the internet or data storage system can be guaranteed to be completely secure.</p>
          <p>5.2. The User agrees and acknowledges that the above-mentioned measures do not guarantee absolute protection and by accessing the Website, the User agrees to assume all risks associated with disclosure of personal information arising due to breach of firewalls and secure server software.</p>
          <p>5.3. The Business undertakes to review the security measures from time to time in light of new and relevant legal and technical developments.</p>
          <p>5.4. The User is aware that personal data may continue to be stored and retained by the Business for the period necessary to carry out the purposes outlined in this Policy unless a longer retention is required under applicable law or until it is no longer necessary for any other legal or Business purposes (whichever is later).</p>

          <h3>6. DISCLOSURE OF PERSONAL INFORMATION</h3>
          <p>6.1. In general, the Business will not disclose personal data except in accordance with the following:</p>
          <ul>
            <li>(a) in order to carry out the purposes for which such personal data was collected; or</li>
            <li>(b) where the User has consented; or</li>
            <li>(c) where permitted under the PDPA or other applicable law or;</li>
            <li>(d) if required by applicable law, including the reporting of suspicious transactions to the authorities in any jurisdiction.</li>
          </ul>
          <p>6.2. You should be aware that Ethereum and other cryptocurrencies are not necessarily truly anonymous. Generally, anyone can see the balance and transaction history, public keys of any address on the Ethereum blockchain. We, and any others who can match your public address to other information about you, may be able to identify you from a blockchain transaction. This is because, in some circumstances, information published on a block chain (such as your public key and IP address) can be correlated with information that we and others may have. This may be the case even if we, or they, were not involved in the blockchain transaction. Furthermore, by using data analysis techniques on a given blockchain, it may be possible to identify other information about you. As part of our security, anti-fraud, anti-money laundering and/or identity verification and authentication checks, the Business may conduct such analysis to collect and process such information about you. you acknowledge and agree to allow us to perform such practices.</p>

          <h3>7. THIRD PARTY USER EXPERIENCE IMPROVEMENT SERVICES</h3>
          <p>7.1. The Business may use third party services and applications to better understand the behaviour of the Users of the Website. Where your consent has been provided, the personal data you provide to us may be transferred to third parties as may be advised to you, either within or outside Singapore, as may be necessary for any of the purposes stated above. Our contracts with these third parties will include the necessary provisions to safeguard the personal data that is being transferred to them.</p>
          <p>7.2. A User’s relationship with these third parties and their services and tools is independent of the User’s relationship with the Business. These third parties may allow the User to permit/ restrict the information that is collected and it may be in the User’s interest to individually restrict or enable such data collections. The place of processing depends on each third party service provider and the User may wish to check the privacy policy of each of these service providers to identify how much data is shared and why.</p>

          <h3>8. THIRD PARTY AUTHENTICATION SERVICES</h3>
          <p>8.1. The Business may use third party authentication services. In such cases, We may be privy to, granted access to and/ or store, certain data available with these third parties for registration and identification purposes.</p>
          <p>8.2. The place of processing depends on each third party service provider and you may wish to check the privacy policy of each of these service providers to identify how much data is shared and why.</p>

          <h3>9. THIRD PARTY LINKS</h3>
          <p>9.1. We may, at our discretion, include third party products or services on the Website that are not operated by Us. These third party sites have separate and independent privacy policies. We have no control over, and therefore assume no responsibility or liability for the content and activities of these linked websites. We strongly advise you to review the privacy policy of every site you visit.</p>

          <h3>10. THIRD PARTY STORAGE</h3>
          <p>10.1. The Business and the Website may use international web hosting facilities and cloud server services which are maintained in accordance with tight security standards.</p>

          <h3>11. TRANSFER OF PERSONAL DATA OUTSIDE SINGAPORE</h3>
          <p>11.1. We may store and process your personal information in data centres around the world, wherever the service providers are located. As such, we may transfer your personal data outside Singapore. Such transfers are undertaken in accordance with applicable laws and regulatory obligations.</p>

          <h3>12. BUSINESS TRANSITIONS</h3>
          <p>12.1. The User is aware that in the event the Business goes through a transition, such as a merger, acquisition by another organisation, or sale of all or a portion of its assets, the Users’ personal data might be among the assets transferred as a result of the Business transition.</p>

          <h3>13. ACCESS TO AND CORRECTION OF INFORMATION</h3>
          <p>13.1. Under the terms of the PDPA, you have the right to ascertain whether we hold your accurate and current information, and the right to access and correct your personal data. you may exercise this right by contacting us at the contact details provided below.</p>
          <p>13.2. When handling a data access or correction request, We check the identity of the requesting party to ensure that he or she is the person legally entitled to make such request. A reasonable fee may be charged to cover our administrative costs incurred for complying with your data access request.</p>

          <h3>14. WITHDRAWAL OF CONSENT TO USE your PERSONAL DATA</h3>
          <p>14.1. You may withdraw your consent for us to use your personal data at any time by contacting us as directed below. We shall stop using your personal data and ensure that the parties to whom We transferred your personal data in accordance with paragraphs 5, 6, 10, 11 and 12, will comply with your request. If you only wish to stop receiving marketing or promotional materials and information from us, please contact us as indicated below.</p>

          <h3>15. WITHDRAWAL OF CONSENT TO USE your PERSONAL DATA</h3>
          <p>15.1. The Business reserves its right to revise, modify and update this Policy at any time, without prior notice, at the sole discretion of the Business.</p>
          <p>15.2. The Business undertakes to notify the Users on the Website in the event the Policy is revised and make available the revised Policy.</p>

          <h3>16. WITHDRAWAL OF CONSENT TO USE your PERSONAL DATA</h3>
          <p>
            Please send any questions or requests in relation to the Policy to:
          </p>
          <h4>Email: contact@cubego.io</h4>
          <p>To facilitate any request in respect of your personal data, you should indicate “PDPA Request” in your email or other communication to us.</p>

        </Container>

        <Footer size={Container.sizes.SMALL}/>
      </PageWrapper>
    )
  }
}

const mapStateToProps = (store, props) => {
  let pathName = props.location.pathname;

  return {
    pathName,
    _t: getTranslate(store.localeReducer),
  }
};

const mapDispatchToProps = (dispatch) => ({
  dispatch: dispatch,
});

export default withRouter(connect(
  mapStateToProps,
  mapDispatchToProps
)(PrivacyPage));
