import {emptyFnc} from "../utils";

export const getPublicInstance = emptyFnc('getPublicInstance');
export const getRootHostContext = emptyFnc('getRootHostContext');
export const getChildHostContext = emptyFnc('getChildHostContext');
export const prepareForCommit = emptyFnc('prepareForCommit');
export const resetAfterCommit = emptyFnc('resetAfterCommit');
export const createInstance = emptyFnc('createInstance');
export const appendInitialChild = emptyFnc('appendInitialChild');
export const finalizeInitialChildren = emptyFnc('finalizeInitialChildren');
export const prepareUpdate = emptyFnc('prepareUpdate');
export const shouldSetTextContent = emptyFnc('shouldSetTextContent');
export const shouldDeprioritizeSubtree = emptyFnc('shouldDeprioritizeSubtree');
export const createTextInstance = emptyFnc('createTextInstance');
export const scheduleDeferredCallback = emptyFnc('scheduleDeferredCallback');
export const cancelDeferredCallback = emptyFnc('cancelDeferredCallback');
export const scheduleTimeout = emptyFnc('scheduleTimeout');
export const cancelTimeout = emptyFnc('cancelTimeout');
export const noTimeout = emptyFnc('noTimeout');
export const now = emptyFnc('now');
export const isPrimaryRenderer = emptyFnc('isPrimaryRenderer');
export const supportsMutation = emptyFnc('supportsMutation');
export const supportsPersistence = emptyFnc('supportsPersistence');
export const supportsHydration = emptyFnc('supportsHydration');
